version: "3"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /var/www/static:/usr/src/app/static
    environment:
      - VIRTUAL_HOST=table-api.adigame.dev
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=table-api.adigame.dev
      - LETSENCRYPT_EMAIL=sabyrbayev.adi32@gmail.com
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
